Draft: birthday card
SpaceServerUniverse/UniverseCoreV2 pull request #132
Opened 2024-10-08 14:31 UTC by OneWalkDev

2024-10-08 19:47 UTC, m1sk9 commented
間違えてマージしないようにドラフトで作りなさいな

2024-10-15 14:16 UTC, m1sk9 requested changes
Javadoc のミスは `Commit suggestion` って出てるところは押せば自動で直るようにした

![image](https://github.com/user-attachments/assets/c554329d-6a38-493b-8b64-f8ff91c0cbd9)

2024-10-15 14:16 UTC, m1sk9 commented on src/main/java/space/yurisi/universecorev2/subplugins/birthdaycard/command/BirthdayCardCommand.java
> +import java.util.*;
一般的に Import 文に `*` を使うと可読性落ちたり, 名前衝突のリスクがあるので非推奨です. UniverseCoreV2 内のクラスに対して使うのはギリセーフくらい. JVM のライブラリには7割ぶち当たるのでやめたほうがいい)

IDEA には [Optimize Imports (インポート文の最適化)](https://www.jetbrains.com/help/idea/creating-and-optimizing-imports.html#optimize-imports) があってこれを使うと IDEA が必要な Import 文だけを抽出してくれます. 試してみて (エクスプローラからファイル右クリックして出てくるコンテキストメニューにある)

![CleanShot 2024-10-15 at 23 03 15@2x](https://github.com/user-attachments/assets/1f56e7fd-2832-4cc1-b0b1-4a4dc2187cb7)

2024-10-15 14:16 UTC, m1sk9 commented on src/main/java/space/yurisi/universecorev2/subplugins/birthdaycard/menu/birthday_calendar/BirthdayCalendar.java
> +        Item border = new SimpleItem(new ItemBuilder(Material.BLACK_STAINED_GLASS_PANE).setDisplayName(""));
`.setDisplayName("")` 消していいよ

2024-10-15 14:16 UTC, m1sk9 commented on src/main/java/space/yurisi/universecorev2/subplugins/birthdaycard/menu/birthday_calendar/BirthdayCalendar.java
> +                .setTitle("BirthdayCard 2024 (" + months[page] + ")")
これ年部分ハードコードになってるけど来年以降どうするの?

2024-10-15 14:16 UTC, m1sk9 commented on src/main/java/space/yurisi/universecorev2/subplugins/birthdaycard/menu/birthday_calendar_menu/BirthdayCalendarMenu.java
> +        Item border = new SimpleItem(new ItemBuilder(Material.BLACK_STAINED_GLASS_PANE).setDisplayName(""));
ここも `.setDisplayName("")` 消していい

2024-10-15 14:16 UTC, m1sk9 commented on src/main/resources/plugin.yml
> +    description: "お誕生日カード"
```suggestion
    description: お誕生日カードメニューを開きます
```

2024-10-15 18:27 UTC, TATCHAN0825 commented on src/main/java/space/yurisi/universecorev2/subplugins/birthdaycard/command/BirthdayCardCommand.java
> +import java.util.*;
5aa7c80f19a8a2a0f427178cff5b5c752caf6425

2024-10-15 18:28 UTC, TATCHAN0825 commented on src/main/java/space/yurisi/universecorev2/subplugins/birthdaycard/menu/birthday_calendar_menu/BirthdayCalendarMenu.java
> +        Item border = new SimpleItem(new ItemBuilder(Material.BLACK_STAINED_GLASS_PANE).setDisplayName(""));
a9c9bf8459eee3d17323ed61ae2bf6b7d7438299

2024-10-15 18:28 UTC, TATCHAN0825 commented on src/main/java/space/yurisi/universecorev2/subplugins/birthdaycard/menu/birthday_calendar/BirthdayCalendar.java
> +        Item border = new SimpleItem(new ItemBuilder(Material.BLACK_STAINED_GLASS_PANE).setDisplayName(""));
a9c9bf8459eee3d17323ed61ae2bf6b7d7438299

2024-10-15 18:28 UTC, TATCHAN0825 commented on src/main/java/space/yurisi/universecorev2/subplugins/birthdaycard/menu/birthday_calendar/BirthdayCalendar.java
> +                .setTitle("BirthdayCard 2024 (" + months[page] + ")")
94ddba445f5edb189ec1cb03a6df00be0b61e01f

2024-10-15 18:54 UTC, m1sk9 requested changes

2024-10-15 18:54 UTC, m1sk9 commented on src/main/resources/plugin.yml
> +    default: op
```suggestion

  # BirthdayCard
  birthday:
    description: お誕生日カードメニューを開きます
```

たつお, コンフリクト解消するときはちゃんと main の変更確認してね ( #156 で `permissions` の部分は全削除してる)

2024-10-15 18:56 UTC, m1sk9 approved these changes

2024-10-15 18:57 UTC, merged