Dev/yurisi receive box
SpaceServerUniverse/UniverseCoreV2 pull request #152
Opened 2024-10-13 09:41 UTC by OneWalkDev

2024-10-14 05:23 UTC, m1sk9 requested changes

2024-10-14 05:23 UTC, m1sk9 commented on src/main/java/space/yurisi/universecorev2/database/DatabaseManager.java
> +     * @return
```suggestion
     * @return ReceiveBoxRepository 受取ボックスのリポジトリ
```

2024-10-14 05:23 UTC, m1sk9 commented on src/main/java/space/yurisi/universecorev2/database/repositories/ReceiveBoxRepository.java
> +     * @return
```suggestion
     * @return ReceiveBox
```

2024-10-14 05:23 UTC, m1sk9 commented on src/main/java/space/yurisi/universecorev2/database/repositories/ReceiveBoxRepository.java
> +     * @return
```suggestion
     * @return List<ReceiveBox>
```

2024-10-14 05:23 UTC, m1sk9 commented on src/main/java/space/yurisi/universecorev2/database/repositories/ReceiveBoxRepository.java
> +     */
```suggestion
    /**
     * 受取アイテムを更新します
     *
     * @return ReceiveBox
     */
```

2024-10-14 05:23 UTC, m1sk9 commented on src/main/java/space/yurisi/universecorev2/subplugins/receivebox/command/addreceiveCommand.java
> +        }
これ Paper の API 使っちゃうとプレイヤーデータが存在しないプレイヤー ( = Universe に参加したことがないプレイヤー) に対しても送れると思うんだけど違う?

2024-10-14 05:23 UTC, m1sk9 commented on src/main/resources/plugin.yml
> +  #ReceiveBox
```suggestion
  # ReceiveBox
```

2024-10-14 08:12 UTC, OneWalkDev commented on src/main/java/space/yurisi/universecorev2/subplugins/receivebox/command/addreceiveCommand.java
> +        }
逆
getOfflinePlayerがWeb空データ取ってくる
Playerクラス参照

2024-10-15 02:51 UTC, m1sk9 commented on src/main/java/space/yurisi/universecorev2/subplugins/receivebox/command/addreceiveCommand.java
> +        }
なるほど. そうぽい

2024-10-15 02:52 UTC, m1sk9 approved these changes

2024-10-15 02:53 UTC, m1sk9 commented
↑ エレベーターと SubPlugin 登録で被っていたのでどっちも適用して commit しました

2024-10-15 02:53 UTC, merged