Dev/syoyu autocollect
SpaceServerUniverse/UniverseCoreV2 pull request #165
Opened 2024-10-20 10:04 UTC by syoooooooooyu

採掘時直接インベントリにアイテムをぶち込む機能
コマンドで切り替え可(/autocollect, /ac)

2024-10-20 10:41 UTC, syoooooooooyu commented
OFFの時でもスコアボードに”自動収集:OFF”とか余計な情報だすのはよくないと思ったため自動収集モードONのときのみスコアボードに表示させました

2024-10-20 15:31 UTC, m1sk9 requested changes

2024-10-20 15:31 UTC, m1sk9 commented on src/main/java/space/yurisi/universecorev2/subplugins/autocollect/AutoCollect.java
> +        core.getCommand("autocollect").setAliases(aliases);
`plugin.yml` で登録している場合は不要です (Paper が勝手に登録します)

2024-10-20 15:31 UTC, m1sk9 commented on src/main/java/space/yurisi/universecorev2/subplugins/autocollect/AutoCollect.java
> +        core.getCommand("autocollect").setExecutor(new AutoCollectCommand());
nit:

見栄えが悪いので **クラス初期化 -> イベント追加 -> コマンド追加** の順にしておくといいかも

2024-10-20 15:31 UTC, m1sk9 commented on src/main/java/space/yurisi/universecorev2/subplugins/autocollect/event/AutoCollectListener.java
> +import java.util.*;
JVM のライブラリをワイルドカードで import するのはやめてほしい (名前衝突などの可能性がある)

2024-10-20 15:31 UTC, m1sk9 commented on src/main/java/space/yurisi/universecorev2/subplugins/autocollect/event/AutoCollectListener.java
> +public class AutoCollectListener implements org.bukkit.event.Listener {
`org.bukkit.event.Listener` は名前衝突の可能性がない ( 他に `Listener` を持つ Import 文がない) ので直接指定は必要ないと思う

2024-10-20 15:31 UTC, m1sk9 commented on src/main/java/space/yurisi/universecorev2/subplugins/playerinfoscoreboard/task/ScoreBoardTask.java
> +        }
これ職業表示欄とぶつからない?

2024-10-20 15:35 UTC, syoooooooooyu commented on src/main/java/space/yurisi/universecorev2/subplugins/playerinfoscoreboard/task/ScoreBoardTask.java
> +        }
これは確認済みでちゃんと職業欄の下に出るようになってる

2024-10-20 15:45 UTC, m1sk9 commented on src/main/java/space/yurisi/universecorev2/subplugins/playerinfoscoreboard/task/ScoreBoardTask.java
> +        }
OK

2024-10-22 13:08 UTC, OneWalkDev approved these changes

2024-10-22 13:08 UTC, merged