Dev/syoyu achievement
SpaceServerUniverse/UniverseCoreV2 pull request #173
Opened 2024-10-27 14:33 UTC by syoooooooooyu

AchievementStatusとかAchievementDataとかのprivateなコンストラクタを持つクラスを作って使うと結構いい感じになった
コード書いた俺でもどこに何書いたか忘れそうになるくらい脳破壊構造してるからレビュー頑張ってください！！！！！！！！！！！！！

2024-10-27 14:36 UTC, syoooooooooyu commented
一旦はNewSpaceServerのときの実績をすべて実装しました
新しい実績を実装するときもすぐに実装できるような構造にしてます

2024-10-27 14:40 UTC, m1sk9 requested changes

2024-10-27 14:40 UTC, m1sk9 commented on src/main/resources/subplugins/achievement.yml
> +  - 1000
ぴーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー EoL 警察です 
ファイルの最後に改行を入れてください

2024-10-29 14:33 UTC, m1sk9 requested changes

2024-10-29 14:34 UTC, m1sk9 commented on src/main/java/space/yurisi/universecorev2/subplugins/achievement/menu/item/AchievementItem.java
> +            return new ItemBuilder(Material.LIGHT_GRAY_STAINED_GLASS_PANE);
Lore に `運営に連絡してください` とか

2024-10-29 14:43 UTC, syoooooooooyu commented
あこれだけか

2024-10-29 15:05 UTC, m1sk9 approved these changes

2024-10-31 07:49 UTC, meyason approved these changes

2024-10-31 15:09 UTC, m1sk9 commented
@OneWalkDev

2024-11-04 11:46 UTC, OneWalkDev commented on src/main/java/space/yurisi/universecorev2/subplugins/achievement/data/AchievementDataManager.java
> +    public static final String Name_NORMAL = "§f";
順番を合わせて

2024-11-04 12:48 UTC, syoooooooooyu commented
どね

2024-11-04 12:50 UTC, merged