tpp
SpaceServerUniverse/UniverseCoreV2 pull request #41
Opened 2024-09-14 14:47 UTC by meyason

2024-09-14 15:02 UTC, OneWalkDev requested changes

2024-09-14 15:02 UTC, OneWalkDev commented on src/main/resources/db/migration/V2024.09.13.23__create_autotppsetting_table.sql
> +    is_auto_accept BOOLEAN NOT NULL DEFAULT FALSE
ーーーーー,
created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP

2024-09-14 16:35 UTC, OneWalkDev approved these changes

2024-09-15 06:22 UTC, meyason commented
これ今どういう状況？

2024-09-15 07:38 UTC, merged