チェストショップ作成しました
SpaceServerUniverse/UniverseCoreV2 pull request #90
Opened 2024-09-26 09:06 UTC by TATCHAN0825

2024-09-26 15:10 UTC, m1sk9 commented on src/main/java/space/yurisi/universecorev2/subplugins/chestshop/ChestShop.java
> +
```suggestion
```
nit: 改行取ろう

2024-09-26 15:11 UTC, m1sk9 commented on src/main/java/space/yurisi/universecorev2/subplugins/chestshop/utils/SuperMessageHelper.java
`utils/Message.java` に同じ責務を持つクラスがあるからこれを使ってほしい

https://github.com/SpaceServerUniverse/UniverseCoreV2/blob/main/src/main/java/space/yurisi/universecorev2/utils/Message.java

2024-09-26 15:12 UTC, m1sk9 commented on src/main/java/space/yurisi/universecorev2/subplugins/chestshop/utils/ItemDeserializer.java
> +        }
例外を捻り潰して変えちゃダメ (`JsonSyntaxException` が返ってくるのに `IllegalArgumentException` 返すのは NG)

2024-09-26 23:35 UTC, TATCHAN0825 commented on src/main/java/space/yurisi/universecorev2/subplugins/chestshop/ChestShop.java
> +
f76d69edc5daba2530a172ee41752aaf7a680831

2024-09-26 23:42 UTC, TATCHAN0825 commented on src/main/java/space/yurisi/universecorev2/subplugins/chestshop/utils/ItemDeserializer.java
> +        }
6847354eb673a42f541b9d3eb9bff041524775de

2024-09-27 15:51 UTC, TATCHAN0825 commented on src/main/java/space/yurisi/universecorev2/subplugins/chestshop/utils/SuperMessageHelper.java
82542efd4fbbb343991f86e2d04ed371b9700d29

2024-09-27 16:00 UTC, m1sk9 approved these changes

2024-09-27 16:00 UTC, m1sk9 commented
マージしちゃだめだよ

2024-09-28 01:20 UTC, OneWalkDev requested changes

2024-09-28 01:20 UTC, OneWalkDev commented on src/main/java/space/yurisi/universecorev2/subplugins/chestshop/event/block/SignChange.java
> +            }
波動拳！
波動拳！！
昇竜拳！！！！

2024-09-28 02:55 UTC, TATCHAN0825 commented on src/main/java/space/yurisi/universecorev2/subplugins/SubPluginInitializer.java
680a36563691fa87c2003d8abbc29b5f60c6a6e3

2024-09-28 02:55 UTC, TATCHAN0825 commented on src/main/java/space/yurisi/universecorev2/subplugins/chestshop/event/block/SignChange.java
> +        } catch (ChestShopNotFoundException e) {
84eeaa5d397530a3ce0d3d9bc79b86f13193c539

2024-09-28 02:55 UTC, TATCHAN0825 commented on src/main/java/space/yurisi/universecorev2/subplugins/chestshop/utils/NumberUtils.java
> +package space.yurisi.universecorev2.subplugins.chestshop.utils;
e2336ba482f33b3381d3938c07ecfbae08d1b329

2024-09-28 02:55 UTC, TATCHAN0825 commented on src/main/java/space/yurisi/universecorev2/subplugins/chestshop/event/block/SignChange.java
> +            }
19b2438d252df22058dc33e93a64cd516be71842

2024-09-29 03:04 UTC, OneWalkDev approved these changes

2024-09-29 03:04 UTC, merged