fishing_system
SpaceServerUniverse/UniverseCoreV2 pull request #94
Opened 2024-09-27 14:35 UTC by sikiEX

2024-09-27 14:37 UTC, OneWalkDev requested changes

2024-09-27 14:37 UTC, OneWalkDev commented on .run/UniverseCoreV2.run.xml
消せ消せ消せ消せ

2024-09-27 14:37 UTC, OneWalkDev commented on src/main/java/space/yurisi/universecorev2/subplugins/fishingsystem/event/FishEvent.java
定数にして書き直せ

2024-09-29 14:51 UTC, m1sk9 requested changes

2024-09-29 14:51 UTC, m1sk9 commented on src/main/java/space/yurisi/universecorev2/subplugins/fishingsystem/event/FishEvent.java
> +            Bukkit.broadcastMessage("§a餌(" + FishFeed.getFishFeedJapanese(item.getType()) + ")が切れています。");
これ多分プレイヤー側に出すメッセージ

2024-09-29 14:54 UTC, m1sk9 approved these changes

2024-09-29 14:55 UTC, OneWalkDev approved these changes

2024-09-29 14:55 UTC, merged